#!/bin/bash

# Please run initial setup first
# Please run blabla/forticlientsslvpn/64bit/./helper/setup to do the initial setup

# Fred Blaise
# 03.02.2017
# Quick and dirty script to vpnssl with totp

# - get your seeds
# - Create a directory to hold your base32 seed at ~/.seeds and chmod 700
# - create files emea, us and st1 with the respective seed for your user. chown 600.
# - Modify the hardcoded user just below to reflect yours
# - Modify the path to your forticlientssl
# - Launch the script with the target argument.
# - Squeeze your butt.

if [[ ! -f ~/.vpnssl_set ]]; then
	echo "First time running... invoking helper."
	sh ~/apps/forticlientsslvpn/64bit/helper/setup
	echo
	echo "Now, you need to manually edit l.53 to put the proper domain name to connect to."
	exit 0
fi

USER=adminfbi
SEEDDIR=~/.seeds
# move to directory, won't exec otherwise
cd ~/apps/forticlientsslvpn/64bit

echo
echo "Warning: this will kill any existing forticlientssl process. Ctrl-c now if you don't want to continue."
echo

[[ -z $1 ]] && echo "Please enter a target (e.g.: emea, us, st1)" && exit -1
TARGET=$1

# Prevent obvious pb with permissions
[[ "$(stat -c %a $SEEDDIR)" != "700" ]] && echo "Please chown 700 your $SEEDDIR directory. Exiting now." && exit -2
[[ "$(stat -c %a $SEEDDIR/$TARGET)" != "600" ]] && echo "Please chown 600 your $SEEDDIR/$TARGET file. Exiting now." && exit -2

echo -n "Enter your password for $USER: "
read -s PASS
echo

# Kill existing instances if needed
ps ax |grep forticlientsslvpn |grep -v grep | awk {'print $1'} |xargs --no-run-if-empty kill -15 

# based on build -- not necessary for platform that package, but needed for me. Should not hurt anyway.
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/security:/usr/local/lib64:/usr/local/lib
TOTP=$($(which oathtool) -b --totp $(cat ${SEEDDIR}/${TARGET}))

$(which expect)<<EOE
set timeout 20
spawn -ignore HUP ./forticlientsslvpn_cli --server vpn-${TARGET}.your_domain:443 --vpnuser $USER --keepalive
expect "Password for VPN:"
send "${PASS}${TOTP}\n"
expect "Would you like to connect to this server? (Y/N)"
send "Y\n"
expect "STATUS::Tunnel running"
EOE

sleep 1

echo
echo "netstat output"
echo "--------------"
netstat -anp |grep forticlient

echo
echo "process list"
echo "------------"
ps ax |grep -v grep |grep forticlient

# FBI - Relink my ~/.ssh/config 
ln -sf ~/.ssh/config-$TARGET ~/.ssh/config

exit 0
