---
- hosts: localhost
  tasks:

  - name: check on brew
    tags:
      - brew
    stat: 
      path: /usr/local/bin/brew
    register: is_brew

  - name: install brew
    tags:
      - brew
    script: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    when: not is_brew.stat.exists

  - name: install taps
    tags:
      - brew
      - taps
    homebrew_tap:
      name: "{{ item }}"
      state: present
    loop:
      - sambadevi/powerlevel9k
      - caskroom/fonts

  - name: install casks
    tags:
      - brew
      - casks
    homebrew_cask:
      name: "{{ item }}"
      state: present
    loop:
      - keepingyouawake
      - zoomus
      - firefox
      - google-chrome
      - istat-menus
      - homebrew/cask-versions/alfred2
      - iterm2
      - gpg-suite
      - karabiner-elements
      - evernote
      - slack
      - signal
      - spectacle
      - spotify
      - microsoft-office
      - visual-studio-code
      - postman
      - kindle
      # - send-to-kindle
      - docker
      - homebrew/cask-drivers/yubico-yubikey-personalization-gui
      - homebrew/cask-drivers/yubico-yubikey-manager
      - homebrew/cask-drivers/yubico-yubikey-piv-manager
      - osxfuse
      - font-hack-nerd-font
      - font-meslo-nerd-font
      - font-inconsolata
      - font-terminus
      - font-source-code-pro
      - xquartz
      - inkscape
      - hipchat
      - vlc
      - wireshark
      - microsoft-teams
      - synergy-beta
    ignore_errors: yes

  - name: override system vim
    tags:
      - brew
      - formulaes
      - vim
    homebrew:
      name: vim
      state: present
      options: with-override-system-vi

  - name: install formulaes
    tags:
      - brew
      - formulaes
    homebrew:
      name: "{{ item }}"
      state: present
    loop:
      - coreutils
      - zsh
      - cmake
      - bash
      - tmux
      - reattach-to-user-namespace
      - gnupg
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - powerlevel9k
      - bat
      - fzf
      - docker-completion
      - docker-compose-completion
      - docker-compose
      - sleepwatcher
      - sshuttle
      - mosh
      - pam_yubico
      - ykman
      - encfs
      - asciinema
      - jupyter
      - speedtest-cli
      - tree
      - pstree
      - libxdg-basedir
      - htop
      - postgres
      - hexyl

  - name: add local zsh to shells
    tags:
      - zsh
    lineinfile:
      path: /etc/shells
      line: '/usr/local/bin/zsh'
      state: present
    become: true

  - name: Python pips
    tags:
      - python
    pip:
      name: "{{ item }}"
      executable: pip3
    loop:
      - virtualenv
      - powerline-status
      - netifaces

  - name: install oh-my-zsh
    tags:
      - zsh
    script: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"


  - name: clone dotfiles repo
    git:
      # repo: git@github.com:madchap/dotfiles.git
      repo: https://github.com/madchap/dotfiles
      dest: ~/gitrepos/dotfiles
      track_submodules: yes
    ignore_errors: yes

  - name: dotdrop install requirements
    tags:
      - dotdrop
    script: pip3 install -r ~/gitrepos/dotfiles/dotdrop/requirements.txt 
    become: true

  - name: dotdrop install all files
    tags:
      - dotdrop
    script: ~/gitrepos/dotfiles/dotdrop.sh install

  - name: powerlevel9k
    git:
      repo: https://github.com/bhilburn/powerlevel9k.git
      dest: ~/.oh-my-zsh/custom/themes/powerlevel9k

  - name: tmux TPM
    tags:
      - tmux
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

#  - name: copy wombat256 for vim
#    tags:
#      - wombat
#    get_url:
#      url: https://raw.githubusercontent.com/michalbachowski/vim-wombat256mod/master/colors/wombat256mod.vim
#      dest: /usr/share/vim/vim80/colors/wombat256mod.vim
#    become: true
#    ignore_errors: yes

  - name: YouCompleteMe install run
    tags: 
      - ycm
    script: 
      cd ~/.vim/bundle/YouCompleteMe && python3 ./install.py

  - name: fzf install run
    tags:
      - fzf
    script:
      /usr/local/Cellar/fzf/0.17.5/install --key-bindings --completion --no-update-rc

  - name: copy sleepwatcher plist
    tags:
      - sleepwatcher
    file:
      src: ~/gitrepos/misc/osx/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
      dst: ~/Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
      become: true

  - name: enable sleepwatcher at start
    tags:
      - sleepwatcher
    script: /bin/launchctl load -w /Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
    become: true 
      
  - name: enable locate
    tags:
      - locate
    script: /bin/launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
    become: true

  - name: load ssh-auth override
    tags:
      - gpg
    script: launchctl load -F ~/Library/LaunchAgents/link-ssh-auth-sock.plist
  
  - name: load homebrew gpg-agent
    tags:
      - gpg
    script: launchctl load -F ~/Library/LaunchAgents/homebrew.gpg.gpg-agent.plist

  - name: symlink updatedb
    tags:
      - locate
    file:
      src: /usr/libexec/locate.updatedb
      dest: /usr/local/bin/updatedb
      state: link

  - name: VS code press and hold
    tags:
      - vscode
    script: /usr/bin/defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
