----
- hosts: localhost
  tasks:

  - name: check on brew
    tags:
      - brew
    stat: 
      path: /usr/local/bin/brew
    register: is_brew

  - name: install brew
    tags:
      - brew
    script: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    when: not is_brew.stat.exists

  - name: override system vim
    # Xcode needs to run manually 
    tags:
      - brew
      - formulaes
      - vim
    homebrew:
      name: vim
      state: present
      # not needed anymore on mojava?
      # options: with-override-system-vi
    ignore_errors: yes

  - name: install formulaes
    tags:
      - brew
      - formulaes
    homebrew:
      name: "{{ item }}"
      state: present
    loop:
      - whatever
      - dotdrop
      - firefox
      - google-chrome
      - istat-menus
      - alfred
      - iterm2
      - gpg-suite
      - karabiner-elements
      - slack
      - signal
      - spectacle
      - spotify
      # - microsoft-office
      - visual-studio-code
      - postman
      - kindle
      # - send-to-kindle
      - docker
      - osxfuse
      - font-hack-nerd-font
      - font-meslo-nerd-font
      - font-inconsolata
      - font-terminus
      - font-source-code-pro-for-powerline
      - xquartz
      - vlc
      - wireshark
      # - microsoft-teams
      - bitwarden
      - aws-vault
      - alt-tab  
      - coreutils
      - zsh
      - cmake
      - bash
      - tmux
      - reattach-to-user-namespace
      - gnupg
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - powerlevel10k
      - bat
      - fzf
      - docker-completion
      - docker-compose-completion
      - docker-compose
      - sleepwatcher
      # - sshuttle
      - mosh
      - asciinema
      - speedtest-cli
      - tree
      - pstree
      - libxdg-basedir
      - htop
      - postgres
      - hexyl
      - pipx
      - npm
      - vault
      - gist
      - jq
      - wireguard-tools
      - tenv
      - direnv
      - python-setuptools
      - tig
      - gh
      - awscli
      - python
      - yubico-yubikey-manager

  - name: add local zsh to shells
    tags:
      - zsh
    lineinfile:
      path: /etc/shells
      line: '/usr/local/bin/zsh'
      state: present
    become: true
    ignore_errors: yes

  - name: Python pips
    tags:
      - python
    pip:
      name: "{{ item }}"
      executable: pip3
    loop:
      - virtualenv
      - powerline-status
      - netifaces
      - shodan
      - truffleHog
      - awscli

  - name: install oh-my-zsh
    tags:
      - zsh
    script: /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    ignore_errors: yes


  - name: clone dotfiles repo
    git:
      # repo: git@github.com:madchap/dotfiles.git
      repo: https://github.com/madchap/dotfiles
      dest: ~/gitrepos/dotfiles
      track_submodules: yes
    ignore_errors: yes

  - name: dotdrop install requirements
    tags:
      - dotdrop
    script: /usr/local/bin/pip3 install -r /Users/fblaise/gitrepos/dotfiles/dotdrop/requirements.txt 
    become: true
    ignore_errors: yes

  - name: dotdrop install all files
    # need to add computer profile to config.yml
    tags:
      - dotdrop
    script: ~/gitrepos/dotfiles/dotdrop.sh install
    ignore_errors: yes

  - name: powerlevel10k
    git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: ~/.oh-my-zsh/custom/themes/powerlevel10k

  - name: tmux TPM
    tags:
      - tmux
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm

#  - name: copy wombat256 for vim
#    tags:
#      - wombat
#    get_url:
#      url: https://raw.githubusercontent.com/michalbachowski/vim-wombat256mod/master/colors/wombat256mod.vim
#      dest: /usr/share/vim/vim80/colors/wombat256mod.vim
#    become: true
#    ignore_errors: yes

  - name: YouCompleteMe install run
    tags: 
      - ycm
    script: 
      cd ~/.vim/bundle/YouCompleteMe && python3 ./install.py
    ignore_errors: yes

  - name: fzf install run
    tags:
      - fzf
    script:
      /usr/local/Cellar/fzf/0.27.2/install --key-bindings --completion --no-update-rc

  - name: create LaunchDaemons directory
    tags:
      - launchctl
    file:
      path: ~/Library/LaunchDaemons
      state: directory
      mode: 0700

  - name: copy sleepwatcher plist
    tags:
      - launchctl
      - sleepwatcher
    file:
      src: /Users/fblaise/gitrepos/misc/osx/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
      dest: /Users/fblaise/Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
      state: link

  - name: enable sleepwatcher at start
    tags:
      - launchctl
      - sleepwatcher
    script: /bin/launchctl load -w ~/Library/LaunchDaemons/de.bernhard-baehr.sleepwatcher-20compatibility-localuser.plist
      
  - name: enable locate
    tags:
      - launchctl
      - locate
    script: /bin/launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist
    become: true

  - name: load ssh-auth override
    tags:
      - launchctl
      - gpg
    script: /bin/launchctl load -F ~/Library/LaunchAgents/link-ssh-auth-sock.plist
  
  - name: load homebrew gpg-agent
    tags:
      - launchctl
      - gpg
    script: /bin/launchctl load -F ~/Library/LaunchAgents/homebrew.gpg.gpg-agent.plist

  - name: symlink updatedb
    tags:
      - launchctl
      - locate
    file:
      src: /usr/libexec/locate.updatedb
      dest: /usr/local/bin/updatedb
      state: link
    become: true    

  - name: VS code press and hold
    tags:
      - vscode
    script: /usr/bin/defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false
